# Generated by Django 2.1.2 on 2019-02-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
