# Generated by Django 2.1.2 on 2019-02-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gsite', '0003_auto_20190215_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAboutRock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock', models.CharField(help_text='Enter a rock ', max_length=200)),
                ('hardness', models.IntegerRangeField()),
                ('formula', models.TextField()),
                ('Streak', models.CharField(choices=[('Б', 'Белый'), ('Ч', 'Черный')], max_length=30,
                                            verbose_name='полоса, жилка')),
            ],
            options={
                'ordering': ('rock',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='Infobox',
            field=models.ManyToManyField(help_text='заполнение формы для пород и минералов', to='Gsite.InfoAboutRock'),
        ),
    ]
