# Generated by Django 2.1.2 on 2019-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0004_auto_20190215_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoaboutrock',
            name='formula',
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='hardness',
            field=models.IntegerRangeField(verbose_name='Твердость'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='rock',
            field=models.CharField(help_text='Enter a rock ', max_length=200, verbose_name='Порода или минерал'),
        ),
    ]
