# Generated by Django 2.1.2 on 2019-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0005_auto_20190215_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoaboutrock',
            name='color',
            field=models.CharField(max_length=30, null=True, verbose_name='Цвет'),
        ),
    ]
