# Generated by Django 2.1.2 on 2019-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0008_auto_20190215_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoaboutrock',
            name='category',
            field=models.CharField(max_length=40, null=True, verbose_name='Категория'),
        ),
    ]
