# Generated by Django 2.1.2 on 2019-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0014_auto_20190215_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoaboutrock',
            name='Opacity',
            field=models.CharField(max_length=50, null=True, verbose_name='Прозрачность'),
        ),
    ]
