# Generated by Django 2.1.2 on 2019-02-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gsite', '0015_infoaboutrock_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Infobox',
            field=models.ManyToManyField(blank=True, help_text='заполнение формы для пород и минералов', null=True,
                                         to='Gsite.InfoAboutRock'),
        ),
    ]
