# Generated by Django 2.1.2 on 2019-02-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gsite', '0016_auto_20190215_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Cleavage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Спайность'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='CristalSystem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кристаллография'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Fracture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Трещиноватость'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Lustre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Блеск'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Opacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Прозрачность'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='SpecificGravity',
            field=models.IntegerRangeField(blank=True, null=True, verbose_name='Удельный вес'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Streak',
            field=models.CharField(blank=True, choices=[('Белый', 'Белый'), ('Черный', 'Черный')], max_length=30,
                                   null=True, verbose_name='полоса, жилка'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='Формула'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='hardness',
            field=models.IntegerRangeField(blank=True, null=True, verbose_name='Твердость'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='rock',
            field=models.CharField(blank=True, help_text='Enter a rock ', max_length=200,
                                   verbose_name='Порода или минерал'),
        ),
    ]
