# Generated by Django 2.1.2 on 2019-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0017_auto_20190215_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Infobox',
            field=models.ManyToManyField(blank=True, help_text='заполнение формы для пород и минералов', to='Gsite.InfoAboutRock'),
        ),
    ]
