# Generated by Django 2.1.2 on 2019-04-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0019_auto_20190405_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoaboutrock',
            name='place',
            field=models.ManyToManyField(blank=True, help_text='местоположение', to='Gsite.Place'),
        ),
    ]
