# Generated by Django 2.1.2 on 2019-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0020_infoaboutrock_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoaboutrock',
            name='place',
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.ManyToManyField(blank=True, help_text='местоположение', to='Gsite.Place'),
        ),
    ]
