# Generated by Django 2.1.2 on 2019-04-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0021_auto_20190405_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.ManyToManyField(blank=True, help_text='местоположение', to='Gsite.Place', verbose_name='Местоположение'),
        ),
    ]
