# Generated by Django 2.1.2 on 2019-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0022_auto_20190405_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.ManyToManyField(blank=True, help_text='местоположение', to='Gsite.Place'),
        ),
    ]
