# Generated by Django 2.1.2 on 2019-04-08 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0023_auto_20190405_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Cleavage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Спайность'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='CristalSystem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кристаллография'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Fracture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Трещиноватость'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Lustre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Блеск'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Opacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Прозрачность'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='SpecificGravity',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Удельный вес'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='color',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='infoaboutrock',
            name='hardness',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Твердость'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите тэг', to='Gsite.Tags'),
        ),
    ]
