# Generated by Django 2.1.2 on 2019-04-08 08:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0024_auto_20190408_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
