# Generated by Django 2.1.2 on 2019-04-08 08:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0025_auto_20190408_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
