# Generated by Django 2.1.2 on 2019-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0027_auto_20190408_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoaboutrock',
            name='Streak',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='полоса, жилка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
