# Generated by Django 2.1.2 on 2019-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0028_auto_20190408_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoaboutrock',
            name='density',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Плотность'),
        ),
    ]
