# Generated by Django 2.1.2 on 2019-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0029_infoaboutrock_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ImgForInfobox',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
