# Generated by Django 2.1.2 on 2019-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gsite', '0030_post_imgforinfobox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ImgForInfobox',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
